AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    CodeUri: ./bin
    Runtime: go1.x

Resources:
  GetAllRegions:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-cities
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /cities
            Method: GET

  GetMoviesInCity:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-movies
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /movies/{regionCode}
            Method: GET